In [1]:
import numpy as np

## Numpy Important Methods

- `np.array()`: Cria um array numpy a partir de uma lista.
- `np.arange()`: Cria um array numpy com valores de um intervalo e um passo definidos.
- `np.linspace()`: Cria um array numpy com valores de um intervalo, com um número de elementos definido.
- `np.zeros()`: Cria um array numpy com valores 0.
- `np.ones()`: Cria um array numpy com valores 1.
- `np.eye()`: Cria um array numpy com valores 0, exceto na diagonal principal, que tem valor 1.
- `np.random.rand()`: Cria um array numpy com valores aleatórios entre 0 e 1.
- `np.random.randn()`: Cria um array numpy com valores aleatórios de uma distribuição normal.
- `np.random.randint()`: Cria um array numpy com valores aleatórios inteiros entre um intervalo definido.


In [26]:
arr_1 = np.array([i for i in range(16)])
print(f"\nShape: {arr_1.shape}, Type: {arr_1.dtype}")
print(arr_1)

arr_zeros = np.zeros((4, 4))
print(f"\nShape Matriz Nula: {arr_zeros.shape}, {arr_zeros.dtype}")
print(arr_zeros)

arr_ones = np.ones((4, 4))
print(f"\nShape Matriz : {arr_ones.shape}, {arr_ones.dtype}")
print(arr_ones)

arr_eye = np.eye(4)
print(f"\nShape Matriz Diagonal: {arr_eye.shape}, {arr_eye.dtype}")
print(arr_eye)

arr_rand = np.random.random((4, 4))
print(f"\nShape Matriz Random: {arr_rand.shape}, {arr_rand.dtype}")
print(arr_rand)


Shape: (16,), Type: int64
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Shape Matriz Nula: (4, 4), float64
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Shape Matriz : (4, 4), float64
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Shape Matriz Diagonal: (4, 4), float64
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Shape Matriz Random: (4, 4), float64
[[0.07987134 0.60250254 0.36136225 0.92738421]
 [0.22822035 0.6934925  0.28162894 0.99846029]
 [0.36677089 0.38933516 0.48529685 0.07695375]
 [0.79101412 0.95063049 0.34282723 0.97331292]]


In [33]:
data = np.loadtxt("../0_datasets/numpy/apples_ts.csv", delimiter=",", skiprows=1, usecols=np.arange(1, 88, 1))
data

array([[ 79.72,  81.08,  79.68,  79.8 ,  80.63,  80.8 ,  80.28,  78.99,
         76.77,  76.09,  76.36,  77.16,  77.5 ,  79.03,  80.28,  80.05,
         78.11,  76.9 ,  77.68,  76.05,  75.53,  73.39,  78.36,  89.16,
        105.43, 104.82, 101.15,  98.63,  99.96,  97.29,  98.64, 104.26,
        102.63,  98.64,  97.17,  98.09, 103.07, 110.26, 110.84, 112.28,
        111.1 , 110.06, 113.7 , 112.88, 102.08,  95.54,  91.33,  89.99,
         91.44,  93.51,  93.6 ,  93.78,  98.91, 121.76, 129.6 , 127.9 ,
        114.55, 101.88,  99.09, 103.35, 106.58, 108.  , 114.95, 121.17,
        122.48, 127.58, 131.89, 129.36, 104.26,  93.45,  92.93,  96.15,
         99.1 , 103.  , 103.31, 103.01, 107.37, 116.91, 125.29, 123.94,
        113.03, 102.19,  97.83, 101.07, 103.44, 108.23, 110.28],
       [ 42.67,  44.37,  44.73,  46.75,    nan,  51.59,  57.8 ,  62.14,
         56.76,  50.85,  46.43,  46.73,  45.85,  49.25,  48.14,  49.18,
         49.49,  49.83,  49.14,  63.21,  61.2 ,  60.34,  62.2 ,  74.2 ,

In [30]:
print(data.ndim) #
print(data.size) #
print(data.shape) #

2
435
(5, 87)


In [34]:
data_transposed = data.T
print(data_transposed.shape)
data_transposed

(87, 5)


array([[ 79.72,  42.67,  62.55,  48.26,  71.25],
       [ 81.08,  44.37,  62.73,  51.01,  71.35],
       [ 79.68,  44.73,  63.43,  50.91,  70.9 ],
       [ 79.8 ,  46.75,  63.83,  53.94,  71.92],
       [ 80.63,    nan,  66.06,  61.27,  72.91],
       [ 80.8 ,  51.59,  69.22,  65.44,  74.39],
       [ 80.28,  57.8 ,  72.07,  56.51,  73.1 ],
       [ 78.99,  62.14,  69.31,  53.  ,  70.24],
       [ 76.77,  56.76,  65.18,  43.87,  69.12],
       [ 76.09,  50.85,  62.13,  42.12,  68.98],
       [ 76.36,  46.43,  64.17,  43.98,  68.58],
       [ 77.16,  46.73,  65.5 ,  44.66,  69.5 ],
       [ 77.5 ,  45.85,  66.85,  47.73,  70.14],
       [ 79.03,  49.25,  68.38,  52.31,  70.58],
       [ 80.28,  48.14,  68.77,  56.8 ,  70.78],
       [ 80.05,  49.18,  69.32,  51.15,  72.78],
       [ 78.11,  49.49,  69.77,  54.63,  72.84],
       [ 76.9 ,  49.83,  70.17,  55.8 ,  74.74],
       [ 77.68,  49.14,  70.76,  57.31,  76.43],
       [ 76.05,  63.21,  75.16,  53.81,  81.2 ],
       [ 75.53,  61.